total_seats: 598
majority: 300
threshold_hurdle: 0.05
sample_size: 100
poll_url: 'https://www.wahlrecht.de/umfragen/index.htm'
caching_filename: '../dat/polls_cached.html'
election_day: '2021-09-26'
uncertainty: 0.1
decay_parameter: 1.1

